gas: "#bcf927"
gas-gt: "#71EFA4"
gas-bpchp: "#128E10"
gas-boiler_large: "#e5194d"
gas-boiler_small: "#ba0b38"
gas-demand: "#bcf927"
electricity-bev_charging: "#e05504"
bev_charging: "#e55c19"
electricity-liion_battery: "#b41de6"
heat_central-demand: "#E76F51"
heat_central-import: "#E78751"
heat_central-export: "#E78751"
heat_central-district_heating_storage: "#185421"
heat_decentral-demand: "#f2740a"
heat_decentral-buffer_storage: "#0e2357"
gas-excess: "#DBDBDB"
gas-shortage: "#DBDBDB"
electricity-shortage: "#DADADA"
electricity-curtailment: "#DADADA"
heat_central-excess: "#DBDBDB"
heat_central-shortage: "#DBDBDB"
heat_decentral-excess: "#DBDBDB"
heat_decentral-shortage: "#DBDBDB"
other: "#7f7f7f"

gas-import: "#cfcfcf"
gas-export: "#a0a0a0"

electricity-demand: "#1a6b63"
electricity-import: "#1a687a"
electricity-export: "#1a687a"

electricity-heatpump_river_large: "#12a199"
electricity-heatpump_geo_large: "#9912a1"
electricity-heatpump_small: "#d44fcb"
electricity-pth: "#5c1a8a"

solar-pv_roof: "#f7c920"
solar-pv_facade: "#b39810"
solar-solarthermal: "#d9a90d"

heat_central-aquifer_storage:     "#00B4D8"