gas: "#bcf927"
gas-gt: "#71EFA4"
gas-bpchp: "#128E10"
gas-boiler_large: "#e5194d"
gas-boiler_small: "#ba0b38"
gas-import: "#cfcfcf"
gas-export: "#cfcfcf"
gas-demand: "#bcf927"
electricity-bev_charging: "#e05504"
bev_charging: "#e55c19"
electricity-demand: "#3e89f4"
electricity-import: "#737a8c"
electricity-export: "#737a8c"
electricity-liion_battery: "#b41de6"
electricity-heatpump_river_large: "#12a199"#"#9912A1"
electricity-heatpump_geo_large: "#9912a1"
electricity-heatpump_small: "#964e8c"
electricity-pth: "#8d4e96"
heat_central-demand: "#ff0800"
heat_central-import: "#e2c319"
heat_central-export: "#e2c319"
heat_central-district_heating_storage: "#185421"
heat_central-aquifer_storage: "red"    ##0e574f"
heat_decentral-demand: "#f2740a"
heat_decentral-import: "#e2c319"
heat_decentral-export: "#e2c319"
heat_decentral-buffer_storage: "#0e2357"

solar-pv_roof: "#b39810"
solar-pv_facade: "#f7c920"
solar-solarthermal: "#d9a90d"
wind-onshore: "#19c5e5"

gas-excess: "#DBDBDB"
gas-shortage: "#DBDBDB"
electricity-shortage: "#DADADA"
electricity-curtailment: "#DADADA"
heat_central-excess: "#DBDBDB"
heat_central-shortage: "#DBDBDB"
heat_decentral-excess: "#DBDBDB"
heat_decentral-shortage: "#DBDBDB"

other: "#7f7f7f"