h2: "#bcf927"
h2-gt: "#71EFA4"
h2-bpchp: "#128E10"
h2-extchp: "#c0e519"
h2-boiler_large: "#e5194d"
h2-boiler_small: "#ba0b38"
h2-import: "#cfcfcf"
h2-export: "#cfcfcf"
h2-demand: "#bcf927"
electricity-bev_charging: "#e05504"
bev_charging: "#e55c19"
electricity-demand: "#3e89f4"
electricity-import: "#737a8c"
electricity-export: "#737a8c"
electricity-liion_battery: "#b41de6"
electricity-heatpump_river_large: "#9912A1"
electricity-heatpump_river_small: "#630d69"
electricity-heatpump_geo_large: "#9912a1"
electricity-heatpump_small: "#964e8c"
electricity-pth: "#8d4e96"
heat_central-demand: "#ff0800"
heat_central-import: "#e2c319"
heat_central-export: "#e2c319"
heat_central-district_heating_storage: "#185421"
heat_central-aquifer_storage: "#0e574f"
heat_decentral-demand: "#f2740a"
heat_decentral-import: "#e2c319"
heat_decentral-export: "#e2c319"
heat_decentral-buffer_storage: "#0e2357"

solar-pv: "#dea923"
solar-pv_roof: "#b39810"
solar-pv_facade: "#baa634"
wind-onshore: "#19c5e5"
hydro-reservoir: "#4a19e5"
hydro-ror: "#6d19e5"

h2-excess: "#DBDBDB"
h2-shortage: "#DBDBDB"
electricity-shortage: "#DADADA"
electricity-curtailment: "#DADADA"
heat_central-excess: "#DBDBDB"
heat_central-shortage: "#DBDBDB"
heat_decentral-excess: "#DBDBDB"
heat_decentral-shortage: "#DBDBDB"

other: "#7f7f7f"

biomass: "#2ca02c"
biomass-gt: "#2ca02c"
biomass-st: "#007000"
hard coal: "black"
lignite: "saddlebrown"
oil: "#9467bd"
oil-gt: "#4a335e"
nuclear: "pink"