general:
  prepare_resources_locally: True
  plot_filetype: .png
  ts_index_name: id_ts
  scal_index_name: id_scal
  separator: ";"

labels: de

build_datapackage:
  el_gas_relation: electricity_gas_relation  # appears in optimize as well
  emission: emission
  additional_scalars_file: additional_scalars.csv
  overwrite_name: false

optimize:
  filename_metadata: datapackage.json
  solver: gurobi
  solve_kwargs:
    tee: True
    keepfiles: True
  write_lp_file: False
  cmdline_options:
    MIPGap: 0.01
  debug: true
  receive_duals: false
  el_gas_relation: electricity_gas_relation  # appears in build_datapackage as well
  el_key: electricity  # prefix of keywords for gas electricity relation
  gas_key: gas  # prefix of keywords for gas electricity relation


plot_scalar_results:
  agg_regions: true
  ignore_drop_level: "var_name"
  tick_label_size: 12

prepare_cop_timeseries:
  quality_grade_air_source: 0.4
  quality_grade_water_source: 0.5
  quality_grade_ground_source: 0.5
  ground_source_temperature: 21
  scenario: ALL

prepare_electricity_demand:
  regions: [AD]
  ts_var_unit: None
  var_name: electricity-demand-profile

prepare_feedin:
  years: [2050]
  region: AD
  ts_var_unit: None
  ts_source: Wista Management
  ts_comment: TRY mean RCP 8.5
  total_roof_area: 310125
  efh_roof_area: 36372
  ghd_mfh_roof_area: 273753

prepare_vehicle_charging_demand:
  ts_var_unit: None
  ts_source: https://github.com/rl-institut/simbev
  ts_comment: created with simBEV. contains a mix of hourly simBEV and a constant profile
  home_start: "15:00"  # start charging strategy "balanced" for home profile
  home_end: "05:00"  # end charging strategy "balanced" for home profile
  work_start: "06:00"  # start charging strategy "balanced" for work profile
  work_end: "14:00"  # end charging strategy "balanced" for work profile
  region_dict: {Adlershof: AD}
  var_name: electricity-bev_charging-profile
  rescaling_factor: 0.000150594

process_re_potential:
  var_unit: MW
  source: area potentials - https://sandbox.zenodo.org/record/746695/
  var_name: capacity
  scenario_key: ""
  name: None

upload_results_to_oep:
  schema: model_draft

create_empty_scalars:
  non_regional: [
     "capacity_cost",
     "carrier_cost",
     "efficiency",
     "expandable",
     "marginal_cost",
     "electric_efficiency",
     "thermal_efficiency",
     "condensing_efficiency",
     "loss_rate",
     "storage_capacity_cost",
  ]
  wacc: {
      "var_name": "wacc",
      "carrier": "ALL",
      "region": "ALL",
      "tech": "ALL",
      "type": "ALL",
      "var_unit": "None",
  }
  drop_default_scalars: True

create_empty_ts:
  datetime_format: "%Y-%m-%d %H:%M:%S"
  filter_ts: "empty_ts"
  ts_values: "zeros"  # Set to 'zeros' or 'empty'
  overwrite: false


