# oil: Öl  Raises error as "oil" is in "boiler" -> duplicate mappings
oil: Öl
oil-gt: Öl GT
biomass: Biomasse
biomass-gt: Biomasse GT
biomass-st: Biomasse DT
h2: H2
h2-boiler_large: H2 Boiler (Groß)
h2-boiler_small: H2 Boiler (Klein)
h2-bpchp: H2 KWK (Gegendruck)
h2-demand: H2 Bedarf
h2-excess: H2 Überschuss
h2-export: H2 Export
h2-gt: H2 GT
h2-import: H2 Import
h2-shortage: H2 Shortage
electricity-bev_charging: BEV
electricity-curtailment: Abregelung
electricity-demand: Strombedarf
electricity-export: Stromexport
electricity-heatpump_river_large: Flusswasserwärmepumpe
electricity-heatpump_geo_large: oberflächennahe Geothermie
electricity-heatpump_river_small: Flusswasserwärmepumpe (dezentral)
electricity-heatpump_small: Wärmepumpe (Haushalte)
electricity-import: Stromimport
electricity-liion_battery: Großbatterie
electricity-pth: res. PtH
electricity-shortage: Strom
electricity-transmission: Stromübertragung
hard coal: Steinkohle
heat_central-demand: zen. Wärmebedarf
heat_central-excess: zen. Wärmeüberschuss
heat_central-shortage: zen. Wärme Shortage
heat_central-import: zen. Waermeimport
heat_central-export: zen. Wärmeexport
heat_central-district_heating_storage: Druckwärmespeicher
heat_central-aquifer_storage: Aquiferwärmespeicher
heat_decentral-demand: dez. Wärmebedarf
heat_decentral-excess: dez. Wärmeüberschuss
heat_decentral-shortage: dez. Wärme Shortage
heat_decentral-import: dez. Waermeimport
heat_decentral-export: dez. Waermeexport
heat_decentral-buffer_storage: dez. Pufferwärmespeicher
lignite: Braunkohle
nuclear-st: Kernkraftwerk
other: Andere
solar-pv: PV
solar-pv_roof: Dach-PV
solar-pv_facade: Fassaden-PV